version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  # First of all build Front end alone firest to check if All proccess run correctly
  frontend:
    working_directory: ~/my-deploying-Full-Stack-App/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/my-deploying-Full-Stack-App
      - node/install-packages:
          app-dir: ~/my-deploying-Full-Stack-App/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www $S3_BUCKET_FRONTEND
  backend:
    working_directory: ~/my-deploying-Full-Stack-App/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/my-deploying-Full-Stack-App
      - node/install-packages:
          app-dir: ~/my-deploying-Full-Stack-App/udagram-api
      - run:
          name: Build and Archive backend
          command: |-
            npm run build
            printenv > www/.env
            npm run archive
      - aws-cli/install
      - run:
          name: Deploy backend
          command: |-
            aws s3 cp ./www/Archive.zip $S3_BUCKET_SERVER
            aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$EB_BUCKET",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_ENV --version-label <<pipeline.git.revision>>
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - backend
